export const OCCTL_GET_STATUS = "OCCTL_GET_STATUS"
export const OCCTL_GET_STATUS_SUCCESS = "OCCTL_GET_STATUS_SUCCESS"
export const OCCTL_GET_STATUS_ERROR = "OCCTL_GET_STATUS_ERROR"

export const OCCTL_GET_USERS = "OCCTL_GET_USERS"
export const OCCTL_GET_USERS_SUCCESS = "OCCTL_GET_USERS_SUCCESS"
export const OCCTL_GET_USERS_ERROR = "OCCTL_GET_USERS_ERROR"

export const OCCTL_GET_USER = "OCCTL_GET_USER"
export const OCCTL_GET_USER_SUCCESS = "OCCTL_GET_USER_SUCCESS"
export const OCCTL_GET_USER_ERROR = "OCCTL_GET_USER_ERROR"

export const OCCTL_DISCONNECT_USER = "OCCTL_DISCONNECT_USER"
export const OCCTL_DISCONNECT_USER_SUCCESS = "OCCTL_DISCONNECT_USER_SUCCESS"
export const OCCTL_DISCONNECT_USER_ERROR = "OCCTL_DISCONNECT_USER_ERROR"
