export const OCCTL_GET_STATUS = "OCCTL_GET_STATUS"
export const OCCTL_GET_STATUS_SUCCESS = "OCCTL_GET_STATUS_SUCCESS"
export const OCCTL_GET_STATUS_ERROR = "OCCTL_GET_STATUS_ERROR"

export const OCCTL_GET_USERS = "OCCTL_GET_USERS"
export const OCCTL_GET_USERS_SUCCESS = "OCCTL_GET_USERS_SUCCESS"
export const OCCTL_GET_USERS_ERROR = "OCCTL_GET_USERS_ERROR"

export const OCCTL_GET_USER = "OCCTL_GET_USER"
export const OCCTL_GET_USER_SUCCESS = "OCCTL_GET_USER_SUCCESS"
export const OCCTL_GET_USER_ERROR = "OCCTL_GET_USER_ERROR"

export const OCCTL_DISCONNECT_USER = "OCCTL_DISCONNECT_USER"
export const OCCTL_DISCONNECT_USER_SUCCESS = "OCCTL_DISCONNECT_USER_SUCCESS"
export const OCCTL_DISCONNECT_USER_ERROR = "OCCTL_DISCONNECT_USER_ERROR"

export const OCCTL_START = "OCCTL_START"
export const OCCTL_RELOAD = "OCCTL_RELOAD"
export const OCCTL_RESET = "OCCTL_RESET"
export const OCCTL_STOP_NOW = "OCCTL_STOP_NOW"

export const OCCTL_ADD_USER = "OCCTL_ADD_USER"
export const OCCTL_UPDATE_USER = "OCCTL_UPDATE_USER"
export const OCCTL_DELETE_USER = "OCCTL_DELETE_USER"

export const OCCTL_USER_SESSION = "OCCTL_USER_SESSION"
export const OCCTL_USER_SESSION_SUCCESS = "OCCTL_USER_SESSION_SUCCESS"
export const OCCTL_USER_SESSION_ERROR = "OCCTL_USER_SESSION_ERROR"
